title: "Bassam Kamal"
description: "Software Engineer | Game Engine Developer | CS @ UPEI"
url: "https://bbrizly.github.io" 
baseurl: ""                     
markdown: kramdown
theme: minima  # or any other Jekyll-compatible theme, if desired
